sprint3
aksenk/go-yandex-metrics pull request #13
Opened 2024-03-01 19:31 UTC by aksenk

2024-03-18 22:54 UTC, avhitrov requested changes
1. Неверная реализация счетчика. Значение PollCount на сервере должно соответствовать количеству циклов считывания данных и изменяться линейно. При дефолтных значениях - на 5 за каждую отправку данных. В данной реализации счетчик изменяется нелинейно: 5, 15, 30, 50. Это происходит из-за того, что счетчик одновременно инкрементится и в агенте и на сервере. В агенте после каждой успешной отправки счетчик необходимо сбрасывать.
2. При отключении сервера возникает DATA RACE в процессе мягкого шатдауна. Вот лог:
```
==================
WARNING: DATA RACE
Write at 0x00c000094570 by goroutine 8:
  main.main.func1()
      C:/work/src/github.com/aksenk/go-yandex-metrics/cmd/server/main.go:54 +0x2d1

Previous write at 0x00c000094570 by main goroutine:
  main.main()
      C:/work/src/github.com/aksenk/go-yandex-metrics/cmd/server/main.go:61 +0x66e

Goroutine 8 (running) created at:
  main.main()
      C:/work/src/github.com/aksenk/go-yandex-metrics/cmd/server/main.go:37 +0x63a
==================
Found 1 data race(s)
```
3. В процессе работы агента возникают гонки (DATA RACE). Вот лог:
```
==================
WARNING: DATA RACE
Write at 0x00c000108008 by goroutine 9:
  github.com/aksenk/go-yandex-metrics/internal/agent/metrics.GenerateCustomMetrics()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/metrics/metrics.go:40 +0x64
  github.com/aksenk/go-yandex-metrics/internal/agent/app.(*App).GetMetrics()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/app/app.go:99 +0x21a
  github.com/aksenk/go-yandex-metrics/internal/agent/app.(*App).Run.func1()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/app/app.go:52 +0x4f

Previous read at 0x00c000108008 by main goroutine:
  reflect.Value.Int()
      C:/Apps/Go/src/reflect/value.go:1469 +0x205
  encoding/json.intEncoder()
      C:/Apps/Go/src/encoding/json/encode.go:515 +0x18b
  encoding/json.ptrEncoder.encode()
      C:/Apps/Go/src/encoding/json/encode.go:878 +0x373
  encoding/json.ptrEncoder.encode-fm()
      <autogenerated>:1 +0x86
  encoding/json.structEncoder.encode()
      C:/Apps/Go/src/encoding/json/encode.go:706 +0x2bd
  encoding/json.structEncoder.encode-fm()
      <autogenerated>:1 +0xe4
  encoding/json.arrayEncoder.encode()
      C:/Apps/Go/src/encoding/json/encode.go:849 +0x112
  encoding/json.arrayEncoder.encode-fm()
      <autogenerated>:1 +0x86
  encoding/json.sliceEncoder.encode()
      C:/Apps/Go/src/encoding/json/encode.go:822 +0x4a2
  encoding/json.sliceEncoder.encode-fm()
      <autogenerated>:1 +0x86
  encoding/json.(*encodeState).reflectValue()
      C:/Apps/Go/src/encoding/json/encode.go:323 +0x83
  encoding/json.(*encodeState).marshal()
      C:/Apps/Go/src/encoding/json/encode.go:295 +0x184
  encoding/json.Marshal()
      C:/Apps/Go/src/encoding/json/encode.go:162 +0xf0
  github.com/aksenk/go-yandex-metrics/internal/agent/app.(*App).sendBatchMetrics()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/app/app.go:128 +0x284
  github.com/aksenk/go-yandex-metrics/internal/agent/app.(*App).WaitMetrics.func1()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/app/app.go:64 +0x5d
  github.com/aksenk/go-yandex-metrics/internal/retry.(*Retry).Do()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/retry/retry.go:29 +0x81
  github.com/aksenk/go-yandex-metrics/internal/agent/app.(*App).WaitMetrics()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/app/app.go:73 +0x2f2
  github.com/aksenk/go-yandex-metrics/internal/agent/app.(*App).Run()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/app/app.go:53 +0x268
  main.main()
      C:/work/src/github.com/aksenk/go-yandex-metrics/cmd/agent/main.go:61 +0x577

Goroutine 9 (running) created at:
  github.com/aksenk/go-yandex-metrics/internal/agent/app.(*App).Run()
      C:/work/src/github.com/aksenk/go-yandex-metrics/internal/agent/app/app.go:52 +0x24e
  main.main()
      C:/work/src/github.com/aksenk/go-yandex-metrics/cmd/agent/main.go:61 +0x577
==================
```
Скорее всего, структура, содержащая собранные для отправки данные, не защищена блокировкой (мьютекс).

Для фиксации гонок в домашних условиях достаточно скомпилировать обе компоненты с ключом `-race` и запустить во взаимодействие друг с другом.

2024-03-18 22:54 UTC, avhitrov commented on cmd/agent/main.go
> +				log.Fatalf("Gracefull shutdown timeout exceeded, force shutdown")
1. Внутри log.Fatalf и так вызывается `os.Exit(1)`, следующая за этой команда (еще один `os.Exit(1)`) никогда не будет выполнена.
2. При установке log.Fatal, необходимо учитывать, что никакой defer ни в какой функции уже выполнен не будет. Здесь по коду вроде все норм, но не могу не напомнить об этом.

2024-03-20 18:21 UTC, aksenk commented on cmd/agent/main.go
> +				log.Fatalf("Gracefull shutdown timeout exceeded, force shutdown")
> 1. Внутри log.Fatalf и так вызывается `os.Exit(1)`, следующая за этой команда (еще один `os.Exit(1)`) никогда не будет выполнена.

Да, логично, просмотрел.

> 2. При установке log.Fatal, необходимо учитывать, что никакой defer ни в какой функции уже выполнен не будет. Здесь по коду вроде все норм, но не могу не напомнить об этом.

Ага, спасибо. Это я понимаю, поэтому только в main.go использовал на случай когда не можем в целом приложение запустить.

2024-03-21 23:37 UTC, avhitrov requested changes
Гонки исправлены, текст дочитал - практически все хорошо. Только наличие Fatal внутри одной из функций работы со стораджем не позволило пропустить работу дальше. Попутно предлагаю рассмотреть комментарий об использовании пары функций для распечатки голого текста и текста с форматированием и вставкой переменных.

2024-03-21 23:37 UTC, avhitrov commented on internal/server/handlers/handlers.go
> +			log.Errorf("Missing metric type")
```suggestion
			log.Error("Missing metric type")
```
Если в строку, которую должен распечатать логгер, не подставляется хотя бы одна переменная, имеет смысл отказаться от использования в этом случае функций с суффиксом `f`. Они весьма тяжеловесны. Лучше описать по два комплекта на каждый log-level: Info + Infof, Debug + Debugf - и использовать то, что соответствует вызову.

2024-03-21 23:37 UTC, avhitrov commented on internal/server/storage/postgres/postgres.go
> +				p.Logger.Fatalf("Connection error: %s", err)
Упс! Потеря сетевой связанности с постгресом - не повод ронять сервер. Связанность можно восстановить - и данные снова потекут, а вот на упавшем сервере уже ничего не сделаешь. Правильный паттерн - поднять до хендлера ошибку и там вернуть 500. И писать в лог о проблемах.

2024-03-22 20:15 UTC, aksenk commented on internal/server/storage/postgres/postgres.go
> +				p.Logger.Fatalf("Connection error: %s", err)
да, я это исправил еще в прошлый раз, когда ты оставил комментарий по поводу fatal в main.go, но забыл включить в коммит)

у меня Amazon CodeWhisperer стоит, он частенько забирает на себя часть рутинного кода, но иногда такие причуды выдаёт, а я видимо пропустил)

2024-03-24 15:16 UTC, avhitrov approved these changes
Все замечания учтены, отлично!

2024-03-24 16:23 UTC, merged