sprint4
aksenk/go-yandex-metrics pull request #15
Opened 2024-04-08 17:49 UTC by aksenk

2024-04-10 22:11 UTC, avhitrov requested changes
К серверу вопросов нет. Есть вопросы к агенту, в комментариях к коду.

2024-04-10 22:11 UTC, avhitrov commented on internal/agent/app/app.go
> +	psutilRequiredMetrics := []string{"TotalMemory", "FreeMemory", "CPUutilization1"}
В соответствии с заданием метрик CPUutilization должно быть по количеству процессоров. Первым шагом необходимо определить, сколько процессоров есть в системе (не различаем физические и виртуальные) и на базе этого необходимо зарегистрировать метрики CPUutilization1, CPUutilization2, ... CPUutilizationN

2024-04-10 22:11 UTC, avhitrov commented on internal/agent/app/app.go
> +func (a *App) resultHandler(jobs chan<- models.Metric, results <-chan Response) {
Непонятно, для чего в функцию передается jobs

2024-04-10 22:11 UTC, avhitrov commented on internal/agent/app/app.go
> +	reportTicker := time.NewTicker(reportInterval)
По логике работы, кмк, данную инициализацию тикера лучше перенести в Run.

2024-04-10 22:11 UTC, avhitrov commented on internal/agent/app/app.go
> +				result = append(result, psutilMetrics...)
По заданию данные функции должны выполняться каждая в своей горутине. Соответственно, потребуется синхронизация в виде sync.WaitGroup. И защита result каким-нибудь мьютексом.

2024-04-10 22:11 UTC, avhitrov commented on internal/agent/app/app.go
> +//}
Раскомментируй и повесь в качестве альтернативного способа передачи, управляемого отдельным переменной среды и аргументом командной строки. Будет круто.

2024-04-10 22:11 UTC, avhitrov commented on internal/agent/app/app.go
> +			a.Logger.Errorf("Metric %v is successfully sent", result.Name)
А почему `Errorf`?

2024-04-17 21:12 UTC, aksenk commented on internal/agent/app/app.go
> +			a.Logger.Errorf("Metric %v is successfully sent", result.Name)
очепятка

2024-04-17 21:21 UTC, aksenk commented on internal/agent/app/app.go
> +	reportTicker := time.NewTicker(reportInterval)
перенёс

2024-04-17 21:21 UTC, aksenk commented on internal/agent/app/app.go
> +func (a *App) resultHandler(jobs chan<- models.Metric, results <-chan Response) {
убрал

2024-04-17 21:40 UTC, aksenk commented on internal/agent/app/app.go
> +	psutilRequiredMetrics := []string{"TotalMemory", "FreeMemory", "CPUutilization1"}
готово

2024-04-17 22:40 UTC, aksenk commented on internal/agent/app/app.go
> +				result = append(result, psutilMetrics...)
сделал все на каналах, вроде никакие синхронизации не нужны

2024-04-17 22:53 UTC, aksenk commented on internal/agent/app/app.go
> +//}
а давай не будем этого делать?)

- в реальном коде, конечно, можно было бы расширить так функционал, но в реальном коде не будет таких бредовых и противоречивых требований, как тут в заданиях
- если честно, то я уже устал постоянно играть в угадайку с этими заданиями, где нужно самому придумывать как делать (и надеяться что это совпадёт с автотестами) и переписывать постоянно все

я сделал, что просят по заданию, автотесты проходят

на текущий момент уровень моей инициативы из-за этого всего падает с каждым спринтом.  я по прежнему хочу продолжать изучать go, но уже подгорает из-за всех этих недочетов, совершенно не хочу "вылизывать" это все, хочу изучать core-материал из темы и двигаться дальше, тем более что все сроки у меня уже посорваны и есть большая вероятность, что я так и за год не успею уложиться на все спринты))

поэтому я бы предложил закрыть глаза на такой кейс (улучшайзинг кода, который не принесёт мне особо никаких знаний и который совершенно не окупится в коде для курсов, который каждый спринт переписывается на треть)

2024-04-23 21:49 UTC, avhitrov commented on internal/agent/app/app.go
> +//}
Ок

2024-04-23 21:58 UTC, avhitrov approved these changes
Все отлично!

2024-04-24 17:47 UTC, merged